### ISSUE TITLE
Not able to run the demo

### ISSUE THREAD

**Issue by thhck** [solid-contrib/data-modules#55] opened 2023-12-12 18:34 UTC
Step to reproduce:

 -  run the demo instruction from `bookmarks/soukai` , using node v. 20
 - open firefox to `localhost:5173`
 - create a new account on solidcommunity.net
 - go back to the demo and login with that account
 - add a new bookmark
 
 Expected:
  - a new bookmark appear on the list
  
  Actual:
   - no bookmark is added to the list, the console show the following errors:
   
   ```
   [vite] connecting... [client.ts:18:8](http://localhost:5173/@vite/client.ts)
[vite] connected. [client.ts:150:14](http://localhost:5173/@vite/client.ts)
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools [react-dom.development.js:29840:16](http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js)
Could not find Model with name 'Metadata', are you sure it's booted? [Bookmarks.ts:149:16](http://localhost:5173/@fs/home/user/liquid/data-modules/bookmarks/soukai/src/modules/Bookmarks.ts)
Uncaught (in promise) TypeError: factory is undefined
    Bookmarks Bookmarks.tsx:41
[Bookmarks.tsx:41:24](http://localhost:5173/src/components/Bookmarks.tsx)
Could not find Model with name 'Metadata', are you sure it's booted? [Bookmarks.ts:149:16](http://localhost:5173/@fs/home/user/liquid/data-modules/bookmarks/soukai/src/modules/Bookmarks.ts)
Uncaught (in promise) TypeError: factory is undefined
    Bookmarks Bookmarks.tsx:41
[Bookmarks.tsx:41:24](http://localhost:5173/src/components/Bookmarks.tsx)
Could not find Model with name 'Metadata', are you sure it's booted? [Bookmarks.ts:149:16](http://localhost:5173/@fs/home/user/liquid/data-modules/bookmarks/soukai/src/modules/Bookmarks.ts)
🚀 ~ file: Bookmarks.tsx:99 ~ onClick={ ~ form: 
Object { label: "lab", link: "https://umai.noeldemartin.com/", topic: "top" }
[Bookmarks.tsx:83:20](http://localhost:5173/src/components/Bookmarks.tsx)
Uncaught (in promise) TypeError: factory is undefined
    onClick Bookmarks.tsx:84
[Bookmarks.tsx:84:29](http://localhost:5173/src/components/Bookmarks.tsx)
```

**Comment by michielbdejong** [comment] 2024-01-09 08:51
@soltanireza65 can you have a look?

**Comment by soltanireza65** [comment] 2024-01-09 08:56
> Step to reproduce:
> 
> * run the demo instruction from `bookmarks/soukai` , using node v. 20
> * open firefox to `localhost:5173`
> * create a new account on solidcommunity.net
> * go back to the demo and login with that account
> * add a new bookmark
> 
> Expected:
> 
> * a new bookmark appear on the list
> 
> Actual:
> 
> * no bookmark is added to the list, the console show the following errors:
> 
> ```
> [vite] connecting... [client.ts:18:8](http://localhost:5173/@vite/client.ts)
> [vite] connected. [client.ts:150:14](http://localhost:5173/@vite/client.ts)
> Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools [react-dom.development.js:29840:16](http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js)
> Could not find Model with name 'Metadata', are you sure it's booted? [Bookmarks.ts:149:16](http://localhost:5173/@fs/home/user/liquid/data-modules/bookmarks/soukai/src/modules/Bookmarks.ts)
> Uncaught (in promise) TypeError: factory is undefined
>  Bookmarks Bookmarks.tsx:41
> [Bookmarks.tsx:41:24](http://localhost:5173/src/components/Bookmarks.tsx)
> Could not find Model with name 'Metadata', are you sure it's booted? [Bookmarks.ts:149:16](http://localhost:5173/@fs/home/user/liquid/data-modules/bookmarks/soukai/src/modules/Bookmarks.ts)
> Uncaught (in promise) TypeError: factory is undefined
>  Bookmarks Bookmarks.tsx:41
> [Bookmarks.tsx:41:24](http://localhost:5173/src/components/Bookmarks.tsx)
> Could not find Model with name 'Metadata', are you sure it's booted? [Bookmarks.ts:149:16](http://localhost:5173/@fs/home/user/liquid/data-modules/bookmarks/soukai/src/modules/Bookmarks.ts)
> 🚀 ~ file: Bookmarks.tsx:99 ~ onClick={ ~ form: 
> Object { label: "lab", link: "https://umai.noeldemartin.com/", topic: "top" }
> [Bookmarks.tsx:83:20](http://localhost:5173/src/components/Bookmarks.tsx)
> Uncaught (in promise) TypeError: factory is undefined
>  onClick Bookmarks.tsx:84
> [Bookmarks.tsx:84:29](http://localhost:5173/src/components/Bookmarks.tsx)
> ```
I'll try to reproduce this.

**Comment by soltanireza65** [comment] 2024-01-09 10:02
@thhck @michielbdejong 
i just created a new solid account to reproduce the issue.
find it, the issue is actually on https://github.com/pondersource/solid-typeindex-support/issues/3 which is going to be fixed by https://github.com/pondersource/solid-typeindex-support/pull/4

**Comment by soltanireza65** [comment] 2024-01-09 10:19
@thhck 
i just updated the `@solid-data-modules/bookmarks-soukai` on npm.
please update to `0.0.2` and test it again.
please tell me in case anything wrong goes again, i mean it should not, because i reproduced the same senario, with a new POD.
tel me if we can close the issue.

**Comment by michielbdejong** [comment] 2024-01-22 15:00
I just confirmed that the demo is working, closing.

**Closed by michielbdejong** 2024-01-22 15:00 UTC
